language: node_js
node_js:
 - "stable"

notifications:
  email:
    recipients:
      - uo236851@uniovi.es
    on_success: never
    on_success: always

deploy:
  provider: heroku
  api_key:
    secure: 7dd91c82-8298-4b15-a764-b427a5ec64ea
