language: node_js
node_js:
 - "stable"

notifications:
  email:
    recipients:
      - uo236851@uniovi.es
    on_success: change
    on_failure: change
    
deploy:
  provider: heroku
  api_key:
    secure: ***REMOVED***
  app: web-app-videoconferencias
  skip_cleanup: true

script:
   - node app.js &
   - npm test
