language: node_js
node_js:
 - "stable"

notifications:
  email:
    on_success: never
    on_success: always
    recipients:
      - uo236851@uniovi.es
    
deploy:
  provider: heroku
  api_key:
    secure: ***REMOVED***
  app: web-app-videoconferencias
