language: node_js
node_js:
 - "stable"

notifications:
  email:
    recipients:
      - uo236851@uniovi.es
    on_success: never
    on_failure: always
    
deploy:
  provider: heroku
  api_key:
    secure: ***REMOVED***
  app: web-app-videoconferencias

before_script:
  - npm install
script:
  - npm start
  - npm test
