language: node_js
node_js:
 - "stable"

notifications:
  email:
    recipients:
      - uo236851@uniovi.es
    on_success: never
    on_success: always

deploy:
  provider: heroku
  api_key:
    secure: ***REMOVED***
  app: web-app-videoconferencias
